# census income

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [6]:
adult = pd.read_csv('adult.csv', names = ['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
                                          'marital-status', 'occupation',
                'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'target'])

In [7]:
adult

age          workclass  fnlwgt    education educational-num  \
0      Age          Workclass  Fnlwgt    Education   Education_num   
1       50   Self-emp-not-inc   83311    Bachelors              13   
2       38            Private  215646      HS-grad               9   
3       53            Private  234721         11th               7   
4       28            Private  338409    Bachelors              13   
...    ...                ...     ...          ...             ...   
32556   27            Private  257302   Assoc-acdm              12   
32557   40            Private  154374      HS-grad               9   
32558   58            Private  151910      HS-grad               9   
32559   22            Private  201490      HS-grad               9   
32560   52       Self-emp-inc  287927      HS-grad               9   

            marital-status          occupation    relationship    race  \
0           Marital_status          Occupation    Relationship    Race   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

        gender  capital-gain  capital-loss  hours-per-week  native-country  \
0          Sex  Capital_gain  Capital_loss  Hours_per_week  Native_country   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       target  
0      Income  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [8]:
adult.head()

age          workclass  fnlwgt   education educational-num  \
0  Age          Workclass  Fnlwgt   Education   Education_num   
1   50   Self-emp-not-inc   83311   Bachelors              13   
2   38            Private  215646     HS-grad               9   
3   53            Private  234721        11th               7   
4   28            Private  338409   Bachelors              13   

        marital-status          occupation    relationship    race   gender  \
0       Marital_status          Occupation    Relationship    Race      Sex   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  target  
0  Capital_gain  Capital_loss  Hours_per_week  Native_country  Income  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [9]:
adult.tail()

age      workclass  fnlwgt    education educational-num  \
32556  27        Private  257302   Assoc-acdm              12   
32557  40        Private  154374      HS-grad               9   
32558  58        Private  151910      HS-grad               9   
32559  22        Private  201490      HS-grad               9   
32560  52   Self-emp-inc  287927      HS-grad               9   

            marital-status          occupation relationship    race   gender  \
32556   Married-civ-spouse        Tech-support         Wife   White   Female   
32557   Married-civ-spouse   Machine-op-inspct      Husband   White     Male   
32558              Widowed        Adm-clerical    Unmarried   White   Female   
32559        Never-married        Adm-clerical    Own-child   White     Male   
32560   Married-civ-spouse     Exec-managerial         Wife   White   Female   

      capital-gain capital-loss hours-per-week  native-country  target  
32556            0            0             38   United-States   <=50K  
32557            0            0             40   United-States    >50K  
32558            0            0             40   United-States   <=50K  
32559            0            0             20   United-States   <=50K  
32560        15024            0             40   United-States    >50K

In [10]:
adult.shape

(32561, 15)

In [11]:
adult.describe()

age workclass  fnlwgt education educational-num  \
count   32561     32561   32561     32561           32561   
unique     74        10   21648        17              17   
top        36   Private  164190   HS-grad               9   
freq      898     22696      13     10501           10501   

             marital-status       occupation relationship    race gender  \
count                 32561            32561        32561   32561  32561   
unique                    8               16            7       6      3   
top      Married-civ-spouse   Prof-specialty      Husband   White   Male   
freq                  14976             4140        13193   27815  21789   

       capital-gain capital-loss hours-per-week  native-country  target  
count         32561        32561          32561           32561   32561  
unique          120           93             95              43       3  
top               0            0             40   United-States   <=50K  
freq          29849        31041          15216           29169   24719

In [12]:
adult.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
target             0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [15]:
for col in adult.columns:
    if adult[col].dtypes == 'object':
        adult[col] = le.fit_transform(adult[col])

In [16]:
adult.head()

age  workclass  fnlwgt  education  educational-num  marital-status  \
0   73          9   21647         16               16               7   
1   33          6   20690          9                4               2   
2   21          4   10268         11               15               0   
3   36          4   11553          1               13               2   
4   11          4   16170          9                4               2   

   occupation  relationship  race  gender  capital-gain  capital-loss  \
0          15             6     5       2           119            92   
1           4             0     4       1             0             0   
2           6             1     4       1             0             0   
3           6             0     2       1             0             0   
4          10             5     2       0             0             0   

   hours-per-week  native-country  target  
0              94              42       2  
1               4              39       0  
2              34              39       0  
3              34              39       0  
4              34               5       0

In [17]:
x = adult[['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
       'marital-status', 'occupation', 'relationship', 'race', 'gender',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country']]

In [18]:
y = adult.target

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state =42)

In [20]:
model = []

In [22]:
model.append(("LR", LogisticRegression()))
model.append(("LDA", LinearDiscriminantAnalysis()))
model.append(("KNN", KNeighborsClassifier()))
model.append(("CART", DecisionTreeClassifier()))
model.append(("NB", GaussianNB()))

In [23]:
result = []

In [24]:
names = []

In [25]:
from sklearn import model_selection

In [26]:
for name, models in model:
    kfold = model_selection.KFold(n_splits = 10, random_state = 7)
    cv_result = model_selection.cross_val_score(models, x_train, y_train, cv = kfold, scoring = 'accuracy')
    result.append(cv_result)
    names.append(name)
    msg = "%s, %f(%f)"%(name, cv_result.mean().cv_result.std())
    print(msg)

ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

In [27]:
from sklearn.metrics import confusion_matrix

# using Logistic regression

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [31]:
y_pred = classifier_knn.predict(x_test)

In [32]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [33]:
confusion_matrix(y_test, y_pred)

array([[6626,  829],
       [1592,  722]], dtype=int64)

In [34]:
7605/9769

0.7784829562903061

# using KNN classifier

In [35]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier()

In [36]:
y_pred=classifier_knn.predict(x_test)

In [37]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [38]:
confusion_matrix(y_test, y_pred)

array([[6626,  829],
       [1592,  722]], dtype=int64)

In [39]:
(6858+747)/(6858+747+597+1567)

0.7784829562903061

# using Naive Bayes

In [41]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [42]:
y_pred = classifier_nb.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [43]:
confusion_matrix(y_test, y_pred)

array([[6840,  615],
       [1265, 1049]], dtype=int64)

In [44]:
(7078+727)/(7078+727+377+1587)

0.7989558808475791

# using Decision Tree Classifier

In [45]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [46]:
y_pred = classifier_dt.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1])

In [47]:
confusion_matrix(y_test, y_pred)

array([[6486,  969],
       [ 887, 1427]], dtype=int64)

In [48]:
(6471+1443)/(6471+1443+987+871)

0.8098649201801065

# using Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 3, criterion='entropy')
classifier_rf.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [50]:
y_pred = classifier_rf.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 1])

In [51]:
confusion_matrix(y_test, y_pred)

array([[6673,  782],
       [ 882, 1432]], dtype=int64)

In [52]:
(6674+1470)/(6674+1470+781+844)

0.8336574879721568